name: SharpGeoApi build

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Install dependencies
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build app
      run: dotnet build ./src/SharpGeoApi.sln --configuration Release
    # - name: Publish to Docker
    #  uses: elgohr/Publish-Docker-Github-Action@master
    #  with:
    #    name: bertt/sharpgeoapi
    #    username: ${{ secrets.DOCKER_USERNAME }}
    #    password: ${{ secrets.DOCKER_PASSWORD }} 
    #    workdir: src     
    - name: Deploy app to Heroku
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY}}
        APP_NAME: ${{ 'sharpgeoapi' }}
      run: |
        cd ./src
        docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME


